language: python

python:
  - 2.6
  - 2.7
  - 3.6 
  - 3.7

services: sqlite

env:
  - DJANGO=2.1.2 DB=mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=myproject.settings
  - export PYTHONPATH=$HOME/builds/eldelucchi/tutorialwithtravis
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - mysql -e 'create database test;' -u root

script:
  - python manage.py test
  